#!/usr/bin/env bash

# Install command-line tools using Homebrew
brew tap homebrew/versions
brew tap phinze/cask
brew tap thoughtbot/formulae
# brew tap homebrew/versions/postgresql8

brew install brew-cask
brew tap caskroom/versions
brew tap caskroom/fonts

brew install apg
# brew install apple-gcc42
# brew install atk
# brew install autoconf
# brew install automake
# brew install blueutil
# brew install cairo
# brew install cmake
# brew install ctags
# brew install curl
# brew install elasticsearch
# brew install faac
# brew install ffmpeg
# brew install fontconfig
# brew install gdbm
# brew install gdk-pixbuf
# brew install gettext
# brew install ghostscript
brew install git --override-system-gitv2
brew install git-extras
# brew install glib
# brew install gobject-introspection
# brew install gradle
# brew install hicolor-icon-theme
# brew install icu4c
brew install imagemagick
# brew install intltool
# brew install jbig2dec
# brew install lame
# brew install lesstif
# brew install libevent
# brew install libffi
# brew install libtiff
# brew install libyaml
# brew install little-cms2
# brew install mcrypt
brew install memcached
# brew install mercurial
# brew install mogenerator
# brew install mysql
# brew install nginx
brew install node
brew install openssl
# brew install ossp-uuid
# brew install pcre
brew install phantomjs
# brew install pixman
# brew install pkg-config
# brew install postgresql8
brew install postgresql
# brew install python
brew install rbenv
brew install rbenv-gem-rehash
brew install rcm
# brew install readline
brew install reattach-to-user-namespace
brew install redis
brew install ruby-build
# brew install scons
# brew install sqlite
# brew install texi2html
brew install the_silver_searcher
brew install tmux
brew install tree
# brew install unixodbc
# brew install v8
brew install vim --override-system-vi
brew install watch
brew install wget
# brew install x264
# brew install xpdf
# brew install xvid
# brew install xz
# brew install yasm
# brew install zlib

# ZSH
brew install zsh
brew install zsh-completions
brew install zsh-lovers
brew install zsh-syntax-highlighting

# OS X Apps
brew cask install alfred
brew cask install appcleaner
# brew cask install arq
# brew cask install cyberduck
brew cask install dropbox
brew cask install evernote
brew cask install google-chrome
brew cask install google-hangouts
# brew cask install insync
# brew cask install kindle
# brew cask install picasa
# brew cask install slate
brew cask install sublime-text3
# brew cask install tower
# brew cask install the-unarchiver
brew cask install vagrant
# brew cask install vmware-fusion
brew cask install virtualbox
# brew cask install vlc

# Fonts
brew cask install font-roboto
brew cask install font-ubuntu

# PHP
# brew install php55
# brew install composer
# brew install php55-mcrypt
# brew install phpmyadmin
